"""Pieces of an openpilot port: the fingerprint block and checksum code.

:mod:`autodistill_can.emit.port` assembles these into a complete package; this module
holds the two parts worth reading on their own.

The generated checksum function is the real prize. Reproducing a message's
integrity field is the gate every port has to pass before the car will accept a
command, and it is normally days of work. When the solver has identified a named
algorithm the emitted code calls it directly; when it recovered an anonymous
GF(2) map, the bit masks are emitted as a table that computes the same function.
"""

from __future__ import annotations

import keyword
import re
from collections import defaultdict
from typing import IO

from ..analysis.checksum import ChecksumSolution
from ..analysis.fingerprint import Fingerprint
from ..analysis.message import MessageAnalysis
from ..manual import ESSENTIAL_ECU_TYPES

__all__ = ["write_checksum_function", "write_fingerprint"]

_HEADER = '''"""Generated by AutoDistill from a CAN capture. A starting point, not a port.

Everything here is inferred from observed traffic. Signal names that came from
correlation with a reference log are trustworthy; names of the form
SIG_<bit>_<width> are placeholders for fields whose meaning is still unknown.

Before this drives a car:
  - check every signal against the car with cabana or a live plot
  - confirm the safety model in opendbc/safety covers this platform
  - never test control messages anywhere but a closed course
"""
'''


def write_fingerprint(
    fingerprint: Fingerprint,
    out: IO[str],
    *,
    car_name: str = "MYSTERY_CAR",
    bus: int = 0,
    ecu_types: dict[int, str] | None = None,
) -> None:
    """Write the ``FINGERPRINTS`` and ``FW_VERSIONS`` entries."""
    car_name = _car_identifier(car_name)
    out.write("# ---------------------------------------------------------------\n")
    out.write("# Fingerprint: the messages this car broadcasts.\n")
    out.write("# Paste into the platform's `Fingerprints` / FINGERPRINTS entry.\n")
    out.write("# ---------------------------------------------------------------\n")
    out.write(f"FINGERPRINTS = {{\n  CAR.{car_name}: [{{\n")
    messages = fingerprint.buses.get(bus, {})
    out.write(f"    # physical bus {bus}\n")
    entries = ", ".join(
        f"{addr}: {length}" for addr, length in sorted(messages.items())
    )
    out.write(f"    {entries},\n")
    out.write("  }],\n}\n\n")

    if fingerprint.excluded:
        out.write("# Deliberately excluded from the fingerprint:\n")
        for addr, reason in sorted(fingerprint.excluded.items()):
            out.write(f"#   0x{addr:X}: {reason}\n")
        out.write("\n")

    if fingerprint.firmware:
        out.write("# ---------------------------------------------------------------\n")
        out.write("# Firmware versions read from UDS responses in the capture.\n")
        out.write("# These identify the car far more reliably than the message list,\n")
        out.write("# openpilot also needs each ECU type. Types emitted as live entries\n")
        out.write("# are MANUAL facts from vehicle_info.json; unresolved entries remain\n")
        out.write("# commented TODOs because type cannot be inferred from address alone.\n")
        out.write("# ---------------------------------------------------------------\n")

        usable = bool(
            set((ecu_types or {}).values()) & set(ESSENTIAL_ECU_TYPES)
        )
        if usable:
            out.write("FW_VERSIONS = {\n")
            out.write(f"  CAR.{car_name}: {{\n")
            by_address: dict[int, list] = defaultdict(list)
            for response in fingerprint.firmware:
                by_address[response.request_addr].append(response)
            for addr, responses in sorted(by_address.items()):
                payloads = list(dict.fromkeys(bytes(r.payload) for r in responses))
                for response in responses:
                    out.write(
                        f"    # response 0x{response.addr:X} "
                        f"({response.did_name}): {response.text()!r}\n"
                    )
                ecu_type = (ecu_types or {}).get(addr)
                is_live = bool(ecu_type and ecu_type != "unknown")
                prefix = "" if is_live else "# "
                ecu_name = ecu_type if is_live else "TODO"
                source = "  # MANUAL: vehicle_info.json" if is_live else ""
                out.write(
                    f"    {prefix}(Ecu.{ecu_name}, 0x{addr:X}, None): "
                    f"{payloads!r},{source}\n"
                )
            out.write("  },\n}\n\n")
        else:
            out.write("# FW_VERSIONS is deliberately empty until an essential ECU is identified.\n")
            out.write("FW_VERSIONS = {}\n\n")
            out.write("# Observed firmware, waiting on identification:\n")
            by_address = defaultdict(list)
            for response in fingerprint.firmware:
                by_address[response.request_addr].append(response)
            for addr, responses in sorted(by_address.items()):
                payloads = list(dict.fromkeys(bytes(r.payload) for r in responses))
                for response in responses:
                    out.write(
                        f"# response 0x{response.addr:X} "
                        f"({response.did_name}): {response.text()!r}\n"
                    )
                out.write(
                    f"# (Ecu.unknown, 0x{addr:X}, None): {payloads!r}\n"
                )
            out.write("\n")
    else:
        out.write(
            "# No UDS firmware responses were seen in this capture. openpilot\n"
            "# fingerprints most cars by firmware, so collect them by running\n"
            "#   autodistill-can probe --interface can0\n"
            "# which queries each ECU directly (it transmits -- read its warning).\n\n"
        )

    if fingerprint.vin:
        out.write(f"# VIN observed in the capture: {fingerprint.vin}\n\n")


def _car_identifier(text: str) -> str:
    cleaned = re.sub(r"[^0-9A-Za-z_]", "_", text).strip("_").upper()
    cleaned = re.sub(r"_+", "_", cleaned) or "MYSTERY_CAR"
    if cleaned[0].isdigit() or keyword.iskeyword(cleaned.lower()):
        cleaned = f"CAR_{cleaned}"
    return cleaned


def write_checksum_function(
    analysis: MessageAnalysis, out: IO[str], *, function_name: str | None = None
) -> bool:
    """Write Python that reproduces one message's checksum.

    Returns False if the message has no recovered checksum.
    """
    solution = analysis.checksum
    if solution is None:
        return False

    name = function_name or f"checksum_{analysis.addr:03x}"
    out.write(
        f"def {name}(addr: int, data: bytes) -> int:\n"
        f'    """Checksum for 0x{analysis.addr:X} '
        f"(bits {solution.start}..{solution.end - 1}).\n\n"
        f"    Reproduces {solution.n_verified - solution.n_mismatches} of "
        f"{solution.n_verified} captured frames"
        + ("" if not solution.n_mismatches else
           f" -- {solution.n_mismatches} disagree, which is either capture "
           f"corruption or a subtly wrong formula; check before relying on it")
        + ".\n"
        f"    {solution.describe()}\n"
        f'    """\n'
    )

    if solution.method == "algo":
        _write_named_algo(solution, analysis, out)
    else:
        _write_affine(solution, analysis, out)

    out.write("\n\n")
    return True


def _write_named_algo(
    solution: ChecksumSolution, analysis: MessageAnalysis, out: IO[str]
) -> None:
    checksum_byte = solution.start // 8
    length = analysis.length
    if solution.input_selection == "field_zeroed":
        # Blank only the checksum's own bits, keeping the rest of its byte --
        # which on many messages is the rolling counter, and is covered.
        total = length * 8
        keep = ~(((1 << solution.length) - 1) << (total - solution.start - solution.length))
        prelude = (
            f"    masked = (int.from_bytes(data[:{length}], 'big') "
            f"& 0x{keep & ((1 << total) - 1):0{total // 4}X})"
            f".to_bytes({length}, 'big')\n"
        )
        selection = "masked"
    else:
        prelude = ""
        selection = {
            "before": f"data[:{checksum_byte}]",
            "after": f"data[{checksum_byte + 1}:{length}]",
            "zeroed": f"data[:{checksum_byte}] + b'\\x00' + data[{checksum_byte + 1}:{length}]",
            "whole": f"data[:{length}]",
        }[solution.input_selection]

    body = {
        "toyota": (
            f"total = {length} + sum({selection})\n"
            "    while addr:\n"
            "        total += addr & 0xFF\n"
            "        addr >>= 8\n"
            "    return total & 0xFF"
        ),
        "sum8": f"return sum({selection}) & 0xFF",
        "sum8_plus_len": f"return (sum({selection}) + {length}) & 0xFF",
        "sum8_complement": f"return ~sum({selection}) & 0xFF",
        "sum8_twos": f"return -sum({selection}) & 0xFF",
        "hyundai_sum": f"return (256 - (sum({selection}) % 256)) % 256",
        "subaru": f"return (sum({selection}) + (addr & 0xFF) + (addr >> 8)) & 0xFF",
        "xor8": (
            "checksum = 0\n"
            f"    for b in {selection}:\n"
            "        checksum ^= b\n"
            "    return checksum & 0xFF"
        ),
        "nibble_xor4": (
            "checksum = 0\n"
            f"    for b in {selection}:\n"
            "        checksum ^= (b & 0x0F) ^ (b >> 4)\n"
            "    return checksum & 0x0F"
        ),
        "nibble_sum8": (
            "total = 0\n"
            f"    for b in {selection}:\n"
            "        total += (b & 0x0F) + (b >> 4)\n"
            "    return total & 0xFF"
        ),
        "honda": (
            "total = 0\n"
            "    shifted = addr\n"
            "    while shifted:\n"
            "        total += shifted & 0x0F\n"
            "        shifted >>= 4\n"
            f"    for i, b in enumerate({selection}):\n"
            f"        if i == {length - 1}:\n"
            "            total += b >> 4\n"
            "        else:\n"
            "            total += (b & 0x0F) + (b >> 4)\n"
            "    checksum = 8 - total\n"
            "    if addr > 0x7FF:\n"
            "        checksum += 3\n"
            "    return checksum & 0x0F"
        ),
    }.get(solution.algo)

    if body is None:
        params = {
            "crc8_autosar_2f": (0x2F, 0xFF, 0xFF),
            "crc8_j1850": (0x1D, 0xFF, 0xFF),
            # Hyundai's opendbc helper spells this as init_crc=0xFD,
            # xor_out=0xDF, but its register actually starts at their XOR.
            "crc8_hyundai": (0x1D, 0x22, 0xDF),
            "crc8_smbus": (0x07, 0x00, 0x00),
            "crc8_1d": (0x1D, 0x00, 0x00),
        }.get(solution.algo)
        if params is None:  # pragma: no cover - registry and emitter kept in step
            out.write(f"    raise NotImplementedError({solution.algo!r})\n")
            return
        poly, init, xorout = params
        out.write(
            prelude
            + f"    crc = 0x{init:02X}\n"
            f"    for b in {selection}:\n"
            "        crc ^= b\n"
            "        for _ in range(8):\n"
            f"            crc = ((crc << 1) ^ 0x{poly:02X}) & 0xFF "
            "if crc & 0x80 else (crc << 1) & 0xFF\n"
            f"    return crc ^ 0x{xorout:02X}\n"
        )
        return

    out.write(prelude + f"    {body}\n")


def _write_affine(
    solution: ChecksumSolution, analysis: MessageAnalysis, out: IO[str]
) -> None:
    """Emit a solved GF(2) map as a mask table.

    Each output bit is the parity of the payload bits its mask selects. This is
    exactly what the solver found, so it reproduces the checksum whether or not
    the polynomial was ever identified.
    """
    out.write("    # Input bits, MSB-first payload positions, most significant first:\n")
    out.write(f"    input_bits = {solution.input_bits!r}\n")
    out.write("    masks = [\n")
    for mask in solution.masks:
        out.write(f"        0x{mask:0{(len(solution.input_bits) + 3) // 4}X},\n")
    out.write("    ]\n")

    if solution.counter_constants:
        counter = analysis.counter
        assert counter is not None
        out.write("    constants = {\n")
        for value, constant in sorted(solution.counter_constants.items()):
            out.write(f"        {value}: 0x{constant:02X},\n")
        out.write("    }\n")
        out.write(
            f"    counter = (int.from_bytes(data, 'big') >> "
            f"{analysis.length * 8 - counter.start - counter.length}) & "
            f"0x{(1 << counter.length) - 1:X}\n"
            "    constant = constants[counter]\n"
        )
    else:
        constant = 0
        for bit in solution.constants:
            constant = (constant << 1) | bit
        out.write(f"    constant = 0x{constant:02X}\n")

    out.write(
        "\n"
        "    whole = int.from_bytes(data, 'big')\n"
        f"    total_bits = {analysis.length * 8}\n"
        "    packed = 0\n"
        "    for position in input_bits:\n"
        "        packed = (packed << 1) | ((whole >> (total_bits - 1 - position)) & 1)\n"
        "\n"
        "    checksum = 0\n"
        f"    for index in range({solution.length}):\n"
        "        bit = bin(packed & masks[index]).count('1') & 1\n"
        f"        bit ^= (constant >> ({solution.length - 1} - index)) & 1\n"
        "        checksum = (checksum << 1) | bit\n"
        "    return checksum\n"
    )
